export const messages = [
    "Favoriter kommer snart",
    "Har inte riktigt blivit klar med den här knappen va...",
    "Fortfarande inte klar.",
    "Fortfarande inte klar...",
    "Fortfarande inte klar........",
    "Hallå!? Jag gör mitt bästa men du måste chilla lite kan inte jobba när du fortsätter ta på mig sådär",
    "Broooor (de som vet de vet) snälla låt mig vara",
    "Du är bra på att lyssna du va",
    "Vet du vad?",
    "Eftersom du ändå är här så får vi väl hitta på något",
    "Vi kör sten sax påse. Bestäm vilken du väljer innan du klickar nästa gång.",
    "Påse.",
    "Läääääääätt vinst för mig antagligen",
    "Jaha men då var vi ju tillbaka här igen va",
    "Fesk",
    "Här kommer några kul granbaserade skämt om du vill skoja till det med bordsgrannen:",
    "Vad heter en gran som kan rulla?",
    "Hjulgran",
    "Vad säger granen när den blir kall?",
    "Barrrrrrrrrrrr",
    "Vad kallas en explosiv gran?",
    "Gran-at",
    "Vad händer om man kastar en gran i havet?",
    "Inget speciellt... vad trodde du?",
    "Kanske skepparn och Siv kan se öga till öga eller nått idk",
    "Okej nu har jag slut på dåliga skämt",
    "Men du, ska du inte ta och sjunga något?",
    "Jag som nu har suttit och lagt in alla låtarna i denna digitala sångbok har några rekommendationer!",
    "Manusets fel (under övriga) verkar fet och sen Vi har ett resultat Sonat från Slaget om Schlagern verkar ju användbar om man har ett resultat och så...",
    "Okej nu har du klickat lite väl mycket så nu tar det tyvärr stopp.",
    "Vad har du lärt dig av detta då?",
    "Men kanske att det lönar sig ändå",
    "Du vet, att bara klicka en gång till",
    "Att bara prova en gång till, i värsta fall så misslyckas du, och inget händer",
    "I bästa fall så får du en monolog från en knapp",
    "Gör ditt bästa där ute",
    "Det var kul att lära känna dig",
    "Hoppas du har ett fantastiskt liv",
    "Och många oförglömliga spexperioder därän",
    "Puss och kram, önskar en knapp du fortsatte klicka på",
    "Favoriter kommer snart."
];