name: Redeploy

on:
  repository_dispatch:
    types: [redeploy]

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci && cd functions && npm ci && cd ..
      - run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SPEXBIBELN }}
          channelId: live
          projectId: spexbibeln
